version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Assuming your Go app runs on 8080, adjust as needed
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379 # The name of the service (redis) acts as its hostname

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
